// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: protos/chat.proto
#ifndef GRPC_protos_2fchat_2eproto__INCLUDED
#define GRPC_protos_2fchat_2eproto__INCLUDED

#include "protos/chat.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace ChatPackage {

class ChatStream final {
 public:
  static constexpr char const* service_full_name() {
    return "ChatPackage.ChatStream";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status JoinRoom(::grpc::ClientContext* context, const ::ChatPackage::JoinRoomReq& request, ::ChatPackage::JoinRoomRes* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ChatPackage::JoinRoomRes>> AsyncJoinRoom(::grpc::ClientContext* context, const ::ChatPackage::JoinRoomReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ChatPackage::JoinRoomRes>>(AsyncJoinRoomRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ChatPackage::JoinRoomRes>> PrepareAsyncJoinRoom(::grpc::ClientContext* context, const ::ChatPackage::JoinRoomReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ChatPackage::JoinRoomRes>>(PrepareAsyncJoinRoomRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::ChatPackage::ClientMessage, ::ChatPackage::ServerMessage>> ChatStream(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::ChatPackage::ClientMessage, ::ChatPackage::ServerMessage>>(ChatStreamRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::ChatPackage::ClientMessage, ::ChatPackage::ServerMessage>> AsyncChatStream(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::ChatPackage::ClientMessage, ::ChatPackage::ServerMessage>>(AsyncChatStreamRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::ChatPackage::ClientMessage, ::ChatPackage::ServerMessage>> PrepareAsyncChatStream(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::ChatPackage::ClientMessage, ::ChatPackage::ServerMessage>>(PrepareAsyncChatStreamRaw(context, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void JoinRoom(::grpc::ClientContext* context, const ::ChatPackage::JoinRoomReq* request, ::ChatPackage::JoinRoomRes* response, std::function<void(::grpc::Status)>) = 0;
      virtual void JoinRoom(::grpc::ClientContext* context, const ::ChatPackage::JoinRoomReq* request, ::ChatPackage::JoinRoomRes* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void ChatStream(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::ChatPackage::ClientMessage,::ChatPackage::ServerMessage>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ChatPackage::JoinRoomRes>* AsyncJoinRoomRaw(::grpc::ClientContext* context, const ::ChatPackage::JoinRoomReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ChatPackage::JoinRoomRes>* PrepareAsyncJoinRoomRaw(::grpc::ClientContext* context, const ::ChatPackage::JoinRoomReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderWriterInterface< ::ChatPackage::ClientMessage, ::ChatPackage::ServerMessage>* ChatStreamRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::ChatPackage::ClientMessage, ::ChatPackage::ServerMessage>* AsyncChatStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::ChatPackage::ClientMessage, ::ChatPackage::ServerMessage>* PrepareAsyncChatStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status JoinRoom(::grpc::ClientContext* context, const ::ChatPackage::JoinRoomReq& request, ::ChatPackage::JoinRoomRes* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ChatPackage::JoinRoomRes>> AsyncJoinRoom(::grpc::ClientContext* context, const ::ChatPackage::JoinRoomReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ChatPackage::JoinRoomRes>>(AsyncJoinRoomRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ChatPackage::JoinRoomRes>> PrepareAsyncJoinRoom(::grpc::ClientContext* context, const ::ChatPackage::JoinRoomReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ChatPackage::JoinRoomRes>>(PrepareAsyncJoinRoomRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriter< ::ChatPackage::ClientMessage, ::ChatPackage::ServerMessage>> ChatStream(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::ChatPackage::ClientMessage, ::ChatPackage::ServerMessage>>(ChatStreamRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::ChatPackage::ClientMessage, ::ChatPackage::ServerMessage>> AsyncChatStream(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::ChatPackage::ClientMessage, ::ChatPackage::ServerMessage>>(AsyncChatStreamRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::ChatPackage::ClientMessage, ::ChatPackage::ServerMessage>> PrepareAsyncChatStream(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::ChatPackage::ClientMessage, ::ChatPackage::ServerMessage>>(PrepareAsyncChatStreamRaw(context, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void JoinRoom(::grpc::ClientContext* context, const ::ChatPackage::JoinRoomReq* request, ::ChatPackage::JoinRoomRes* response, std::function<void(::grpc::Status)>) override;
      void JoinRoom(::grpc::ClientContext* context, const ::ChatPackage::JoinRoomReq* request, ::ChatPackage::JoinRoomRes* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ChatStream(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::ChatPackage::ClientMessage,::ChatPackage::ServerMessage>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::ChatPackage::JoinRoomRes>* AsyncJoinRoomRaw(::grpc::ClientContext* context, const ::ChatPackage::JoinRoomReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ChatPackage::JoinRoomRes>* PrepareAsyncJoinRoomRaw(::grpc::ClientContext* context, const ::ChatPackage::JoinRoomReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReaderWriter< ::ChatPackage::ClientMessage, ::ChatPackage::ServerMessage>* ChatStreamRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::ChatPackage::ClientMessage, ::ChatPackage::ServerMessage>* AsyncChatStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::ChatPackage::ClientMessage, ::ChatPackage::ServerMessage>* PrepareAsyncChatStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_JoinRoom_;
    const ::grpc::internal::RpcMethod rpcmethod_ChatStream_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status JoinRoom(::grpc::ServerContext* context, const ::ChatPackage::JoinRoomReq* request, ::ChatPackage::JoinRoomRes* response);
    virtual ::grpc::Status ChatStream(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::ChatPackage::ServerMessage, ::ChatPackage::ClientMessage>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_JoinRoom : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_JoinRoom() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_JoinRoom() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status JoinRoom(::grpc::ServerContext* /*context*/, const ::ChatPackage::JoinRoomReq* /*request*/, ::ChatPackage::JoinRoomRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestJoinRoom(::grpc::ServerContext* context, ::ChatPackage::JoinRoomReq* request, ::grpc::ServerAsyncResponseWriter< ::ChatPackage::JoinRoomRes>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ChatStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ChatStream() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_ChatStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ChatStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::ChatPackage::ServerMessage, ::ChatPackage::ClientMessage>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestChatStream(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::ChatPackage::ServerMessage, ::ChatPackage::ClientMessage>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(1, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_JoinRoom<WithAsyncMethod_ChatStream<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_JoinRoom : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_JoinRoom() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::ChatPackage::JoinRoomReq, ::ChatPackage::JoinRoomRes>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ChatPackage::JoinRoomReq* request, ::ChatPackage::JoinRoomRes* response) { return this->JoinRoom(context, request, response); }));}
    void SetMessageAllocatorFor_JoinRoom(
        ::grpc::MessageAllocator< ::ChatPackage::JoinRoomReq, ::ChatPackage::JoinRoomRes>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ChatPackage::JoinRoomReq, ::ChatPackage::JoinRoomRes>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_JoinRoom() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status JoinRoom(::grpc::ServerContext* /*context*/, const ::ChatPackage::JoinRoomReq* /*request*/, ::ChatPackage::JoinRoomRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* JoinRoom(
      ::grpc::CallbackServerContext* /*context*/, const ::ChatPackage::JoinRoomReq* /*request*/, ::ChatPackage::JoinRoomRes* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ChatStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ChatStream() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackBidiHandler< ::ChatPackage::ClientMessage, ::ChatPackage::ServerMessage>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->ChatStream(context); }));
    }
    ~WithCallbackMethod_ChatStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ChatStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::ChatPackage::ServerMessage, ::ChatPackage::ClientMessage>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::ChatPackage::ClientMessage, ::ChatPackage::ServerMessage>* ChatStream(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef WithCallbackMethod_JoinRoom<WithCallbackMethod_ChatStream<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_JoinRoom : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_JoinRoom() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_JoinRoom() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status JoinRoom(::grpc::ServerContext* /*context*/, const ::ChatPackage::JoinRoomReq* /*request*/, ::ChatPackage::JoinRoomRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ChatStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ChatStream() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_ChatStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ChatStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::ChatPackage::ServerMessage, ::ChatPackage::ClientMessage>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_JoinRoom : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_JoinRoom() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_JoinRoom() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status JoinRoom(::grpc::ServerContext* /*context*/, const ::ChatPackage::JoinRoomReq* /*request*/, ::ChatPackage::JoinRoomRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestJoinRoom(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ChatStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ChatStream() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_ChatStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ChatStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::ChatPackage::ServerMessage, ::ChatPackage::ClientMessage>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestChatStream(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(1, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_JoinRoom : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_JoinRoom() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->JoinRoom(context, request, response); }));
    }
    ~WithRawCallbackMethod_JoinRoom() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status JoinRoom(::grpc::ServerContext* /*context*/, const ::ChatPackage::JoinRoomReq* /*request*/, ::ChatPackage::JoinRoomRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* JoinRoom(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ChatStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ChatStream() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->ChatStream(context); }));
    }
    ~WithRawCallbackMethod_ChatStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ChatStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::ChatPackage::ServerMessage, ::ChatPackage::ClientMessage>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* ChatStream(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_JoinRoom : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_JoinRoom() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ChatPackage::JoinRoomReq, ::ChatPackage::JoinRoomRes>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ChatPackage::JoinRoomReq, ::ChatPackage::JoinRoomRes>* streamer) {
                       return this->StreamedJoinRoom(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_JoinRoom() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status JoinRoom(::grpc::ServerContext* /*context*/, const ::ChatPackage::JoinRoomReq* /*request*/, ::ChatPackage::JoinRoomRes* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedJoinRoom(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ChatPackage::JoinRoomReq,::ChatPackage::JoinRoomRes>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_JoinRoom<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_JoinRoom<Service > StreamedService;
};

}  // namespace ChatPackage


#endif  // GRPC_protos_2fchat_2eproto__INCLUDED
